print("*" * 47)
print("           WELCOME TO S3RAPHIM   ")
print("*" * 47)
captain_name = input("What is your name, Captain? ")
print(f"Welcome aboard, Captain {captain_name}.")
flight_number = input("What is your flight number? ")
print(f"flight: {flight_number}")
altitude = float(input("Enter current altitude (ft): "))
print(f"Altitude: {altitude} ft")
airspeed = float(input("Enter current airspeed (knots): "))
print(f"Airspeed: {airspeed} knots")
fuel_remaining = float(input("Enter remaining fuel (L): "))
print(f"Fuel Remaining: {fuel_remaining} L")
print("all systems are operational and ready for your command")
print("have a safe flight!")