# #ADVANCED FLIGHT DATA SLICER(STRING INDEXING AND SLICING)
flight_data = "BA205-LHR-2245-B787-ONTIME-GATEB12-PILOT:J.SMITH-COPILOT:A.JONES-FUEL:18500"
print(f"{"=" * 5} {"ADVANCED FLIGHT DATA SLICER"} {"=" * 5}")
print(f'1. Airline + flight no: \t{flight_data[0:5]}')
print(f'2. First 5 characters: \t\t{flight_data[0:5]}')
gate_index = flight_data.find("GATE")
print(gate_index)
print(f'3. From GATE onwards: \t\t{flight_data[27:]}')
print(f'4. Last 5 characters: \t\t{flight_data[-5:]}')
print(f'5. Without last 10 characters: \t{flight_data[:-10]}')
print(f'6. Full reverse: \t\t{flight_data[::-1]}')
pilot_name_index = flight_data.find("PILOT")
print(pilot_name_index)
print(f'7. Reversed pilot name: \t{flight_data[41:48][::-1]}')
print(f'8. Every 2nd character: \t{flight_data[::2]}')
destination_index = flight_data.find("LHR")
print(destination_index)
print(f'9. Reversed destination: \t{flight_data[6:9][::-1]}')
fuel_index = flight_data.find("FUEL")
print(fuel_index)
print(f'10. Fuel amount: \t\t{flight_data[70:]}')
print(f'11. Reversed co-pilot name: \t{flight_data[57:64][::-1]}')
secret_code = flight_data[::3]
secret_code_length = len(secret_code) * '*'
print(f'12. Secret code: \t\t{secret_code_length}')
print(f'13. LOWERCASE: \t\t\t{flight_data.lower()}')
print(f'14. Capitalize: \t\t{flight_data.capitalize()}')