pilot_name = input("What is your name? ")
flight_number = input("What is your flight number? ")
altitude = float(input("Enter current altitude (ft): "))
airspeed = float(input("Enter current airspeed (knots): "))
fuel_remaining = float(input("Enter remaining fuel (L): "))
engine_temperature = float(input("Enter engine temperature (°C): "))
outside_temperature = float(input("Enter outside temperature (°C): "))
fuel_after_consumption = float(input("Enter fuel after consumption (L): "))
#this line of code calculates the estimated fuel consumption based on current fuel and fuel after consumption.
estimated_flight_time = float(input("Enter estimated flight time (hours): "))
#this line of code calculates the estimated fuel consumption rate based on fuel consumed and estimated flight time.
print("$" * 57)
print("           S3RAPHIM FLIGHT STATUS   ")
print(f"*Pilot Name                          : {pilot_name}")
print(f"*Flight Number                       : {flight_number}")
print(f"*Altitude                            : {altitude} ft")
print(f"*Airspeed                            : {airspeed} knots")
print(f"*Remaining Fuel                      : {fuel_remaining} L")
print(f"*Engine Temperature                  : {engine_temperature} °C")
print(f"*Outside Temperature                 : {outside_temperature} °C")
print(f"*Estimated Flight Time               : {estimated_flight_time} hours")
print(f"*Estimated Fuel Consumption Rate     : {abs(fuel_remaining - fuel_after_consumption):.2f} L/hour")
print("*" * 57)